### ISSUE TITLE
MonetaryCurrency a 'transfer only' resource?

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#12]
This issue relates a lot to our recent Transfer definition. 

> Moving rights to and responsibilities for an economic resource from one agent to another. This does not cover change of location. The exact rights and responsibilities can be defined by an agreement between the agents, which accompanies the resource to be transferred. If not, the rights are assumed to be rights to consume, use, or transfer the resource.

Monetary currencies seem to have certain peculiarity. One can NOT consume them, or NOT even use them, all one can do with it - keep transfering around the rights to a certain share of it.

How about In definitions of more specific types of resources (physical or virtual), we can start marking which types of rights apply to various generic types of resources? At some point we may end up with matrix of types of resources and applicable types of rights!

**Comment by elf-pavlik** [comment]
based on @ahdinosaur definitions in https://github.com/valueflows/valueflows/issues/103

One can only Transfer (rights to) and Transport (between virtual stocks) monetary currency. Transform does NOT seem to apply to this sub class of virtual resources.

**Comment by elf-pavlik** [comment]
Processes also don't involve monetary currencies, except if we define virtual transport of them as a process. They only seem relevant in *Conversation for Action* as tool to influence decision of other parties.

**Comment by fosterlynn** [comment]
Warning: thinking cap not on.

In our code we did end up needing a set of behaviors for resource types, which could become subclasses.  So far, "type of work" and "virtual account".  Toying with something for crypto currency, but not sure yet.  Then we have some configurations on Transfer Type including "is currency", meaning any of the things you are talking about.

So I think we will need something for what you are talking about, but I don't feel ready to think about it right now.  Just giving you the above in case it helps you think about it @elf-pavlik .

**Comment by gcassel** [comment]
>Warning: thinking cap not on.

OMG, I totally have to repurpose that line for *many* situations.  :)

I too think we'll need something for what you are talking about Elf and am not ready to think about it right now.  (But maybe any hour or day now.)

**Comment by ahdinosaur** [comment]
in a way, monetary currencies are "immutable": they cannot change, only be passed around. :)

**Comment by gcassel** [comment]
As far as I can currently tell, you guys are correct about currencies not being directly transformable.  However, that could potentially make readers uneasy, as if issued currencies are immortal (lol) and the supply of them will inevitably increase over time.   I want to take some space to roughly address that.

Even when we're dealing with a centrally issued fiat currency, units can be (intentionally or unintentionally) destroyed by their holders.. and of course, in a mutual credit system, the units (currency) of credits and debits always adds up to zero.   

Also, in any particular relationship, someone may establish a monetary figure for a current debt; but they may end up resolving that debt without using money.  For instance, if my friend and I agree that I owe them $20 for a car ride, I could  "pay that off" by providing services instead of using money.  

This relates to my view that money always indicates credit, and physical or digital representations of money are "merely" signs of that credit.  

I'll quote myself from gitter for further context on "money=credit". (Sorry for verbosity.)

>fiat currencies are really weird. I think their printing and distribution is a sort of stupendously indirect promise or commitment, from the distributor to the recipients, that their possession gives their 'owners' a fairly predictable amount of credit within a community, or nation-state.

>Of course, strong confidence in the currency will make people desire to possess the currency itself, instead of just using small amounts of it to frequently compensate one side of an exchange of resources or services. Since a strong currency can be very quickly and easily used in so many exchanges-- often, being the only "Give" act-- it becomes the most desirable resource to accumulate. (Which is perhaps why the world is broken.)

>ANYWAY: whether we're dealing with fiat currencies, complementary currencies or mutual credit, I think we're talking about types of credit. It's just that with fiat currencies, the credibility of the credit is SO indirectly suggested.

>With all that in mind: I don't think it exactly matters whether it's a printed money or digital currency, because the paper money, coins and the digital representations are all just signs. The money isn't contained in its representation, which is really IMO just a "proof" of ownership? (Or, a proof of usage-right.)

>Almost equivalent to having a receipt for a purchase, in a way.
>^ "a receipt for the purchase of a promise", maybe..

In related thinking, I've begun to think that any complementary currency (**and** any nation-state currency) can be described in many the same terms as a mutual credit system.   I.e.:  if an individual has $70,000 USD,  then the entire economy of USD exchanges is supposed to "owe them" $70,000.     

Of course it's not really a mutual credit system because credits and debits don't add up to zero, and that's an immense problem.   

Sorry if any of this seems tangential.  I've been unexpectedly focused on the concept of money the last day or two.    Anyway:  I certainly think that value flows' definitions and formulae related to currency ought to inherently enable both credits and debits, so that individuals and groups can (if they wish) use any type of credits and debits which add up to 0.

**Comment by elf-pavlik** [comment]
Yesterday we talked with @bhaugen about transferring some other rights than **ownership**, for example **custody**, and days before **use(rship)**. In case of monetary currency seen as resource, can anyone see in practice any other rights to it that one can vf:Transfer, besides**ownership**? Monetary currency seems to me not 'transfer only' but also 'own only' resource.

**Comment by bhaugen** [comment]
Sensorica has custodians for its CAKE bank account. Lots of bank accounts have multiple signers, not all of whom own the account.

**Comment by elf-pavlik** [comment]
> Sensorica has custodians for its CAKE bank account. Lots of bank accounts have multiple signers, not all of whom own the account.

But that seems related to **the account** which I see more of a stock which contains monetary currency. I ask about ownership over the money (digits) **deposited** on that account, not the account itself.

**Comment by bhaugen** [comment]
What's the diff between the money(digits) and the account(stock) in a stock (indirectly identified) resource?

**Comment by bhaugen** [comment]
P.S. the multiple signers can spend the money...

**Comment by elf-pavlik** [comment]
@bhaugen could you please capture *Sensorica CAKE bank account* as use case, putting emphasis on **ownership**, **custody** and who can 'bank transfer' money deposited on it to other accounts. I think we can have more focused discussion about it if we have such well documented use case.

**Comment by bhaugen** [comment]
Will do.

**Comment by elf-pavlik** [comment]
Monetary currency also seems the only resource which can gave negative quantity. In mutual credit currencies all the accounts have sum: 0 so some accounts need to go negative so others an go positive. Time-based currencies seem to behave in similar way: https://github.com/valueflows/valueflows/issues/143#issuecomment-238741540

**Comment by fosterlynn** [comment]
>Monetary currency also seems the only resource which can have negative quantity. In mutual credit currencies all the accounts have sum: 0 so some accounts need to go negative so others an go positive. Time-based currencies seem to behave in similar way:

Makes sense to me.  Any thoughts on the implications of that?

>Accounts for ISO 4217 currencies might also sometimes go below zero?

Ours did recently. :(
