### ISSUE TITLE
Product vs. Service

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#15]
from #14 

Of course use cases should drive our further work, for services we already have [Dental Care](https://github.com/valueflows/valueflows/blob/master/use-cases/dental-care.md) and [many Transportation use cases](https://github.com/valueflows/valueflows/blob/master/use-cases/dental-care.md)

Service seen as Resource seems to fit an output of a Process - [Transportation as Service/Resource or Transportation as Process or both](https://github.com/valueflows/process/issues/9#issuecomment-217015152)

**Comment by fosterlynn** [comment]
>Service seen as Resource seems to fit an output of a Process

This makes sense to me.

**Comment by elf-pavlik** [comment]
from gitter chat

> you don't store existing services in stocks for others to pick them up later
we can grow apples just in case (also hard to stop trees from doing it), store them and than find someone who wants it
we can not make massages and than allow people to take some of them

**Comment by gcassel** [comment]
We can *transfer* rights to products/goods,   but we can only *perform* (or *provide*) services.   Service is act, work, labor.

I'm not well-oriented here now, but I think that the term transfer simply doesn't apply to services.... but it's tricky, because services are *very often* part of an *exchange*.    

I think Exchange will need to be defined in a way which very simply and clearly includes transfers of rights to resources, and providing/ performing services.

**Comment by bhaugen** [comment]
This is all about what I have called Event Types and Lynn wants to rename. It is about the behavior of type of value flow. Services can be part of an exchange but have a different behavior. It's all good. We just need to define the differences.

**Comment by gcassel** [comment]
As mentioned, not well-oriented-- and now I should rewrite...

Exchange may involve the rights to a product/good  *and* the rights to a service.    And the rights to a service certainly can be transferred, the same as any other resource.  It's less common, because services often *happen* before their rights could be transferred.

**Comment by gcassel** [comment]
Based on a bit of gitter with @elf-pavlik :  I'm thinking about Service as something which must be modeled in different ways depending on who's modeling it, and what context they're modeling it in.   Each model has a *perspective*.

As previously alluded, I think that a desired service can be modeled *as a process*.  But Elf has pointed out that it's really important to describe it (and potentially model it) from the perspective of the agent who desires it.  

For instance, if I want someone to deliver apples to me, I can describe a transportation process which changes the "location" attribute of a specific group of apples, or a quantity of interchangeable/ fungible apples.   That's what I want to happen, and may formally Request.

(Let's pretend here that I already own the apples... otherwise there is a *transfer of rights to goods* as well as *providing a delivery service*!   Easily modeled, but more complex.)

A desired Service-- in my terms here, a desired process-- can be described in a specific Request.   **However,** a Request *does not contain* all of the process(es) which the service provider must actually perform, in order to successfully model an Offer or fulfill a Commitment!  

The service provider may start with the Request, and break that down into their own Plan.  A Plan is IMO a process, but probably a complex one, and it's not equivalent to the Request.    A Plan may lead to an Offer.   Of course, the Plan could change after a mutual Commitment and before the delivery of the Service.   

Anyway... it currently seems really important to me to keep the description (and potentially, the modeling) of a desired Service distinct from the modeling of a Service "Plan".  If the requesting agent and the offering agent are closely related, then maybe the models use mostly the same components....   but still, each model has a different perspective.

Hope this seems to be useful food for thought.

**Comment by bhaugen** [comment]
It might be useful to think of this stuff from the viewpoint of citizens of a different economic system.

Some of them maintain a bus, which other people can ride on.

A lot of community resources go into that bus. And a lot of work of the people who maintain and drive the bus. For them the bus is a series of processes.

For the people who ride the bus, it is a nice community service. But if they want the service to continue, they also understand that they have a responsibility to help in some way to maintain the bus.

So how would we model that?

**Comment by bhaugen** [comment]
Some implications of a different economic system:
* even in that different system, the bus will still have some reciprocal claims on the riders.
    * the reciprocity does not need to be settled with money, paid to the bus organization, which pays the driver and the maintainers and for the equipment and energy to propel the bus.
    * it could also be indirect, where the riders provide food and housing and other necessities of life for the drivers and maintenance people and in other ways provide resources for the bus and energy.
    * but one way or another, all of those flows of use value need to organize themselves in such a way that a somewhat balanced economy continues. Or it won't. See Maya, Anasazi, Hopewell, etc.
    * Likewise all of the people involved in those economic flows owe debts to the whole ecosystem around them, which also won't continue without constant care. See us now.

**Comment by elf-pavlik** [comment]
In my chat with @gcassel I tried to emphasise distinction between Transportation as a process, and the primary/motivating output of that process, which we may call Transportation **Service**. In [Bus Trip](https://github.com/valueflows/valueflows/blob/master/use-cases/bus-trip.md) use case @bhaugen called the process *Trip* and the output *Passenger transportation service*.

Also @ahdinosaur wrote YAML example which seems to approach transportation from the output perspective: https://github.com/valueflows/process/issues/9#issuecomment-217674026

When we cast an intent to receive [vf:Request](https://github.com/valueflows/intent/blob/master/Request.md). We may fist focus on what we want to receive - an **output** of some process. If we want to receive it, that means that we care about having it available and we value it. Then realizing: "what I want to receive comes out of a certain process" comes very important. Traversing graph of inputs of that process (work of other people - services, and products), than second degree processes which yielded those resources, and so on and so on. We may find a way how to contribute to the process, which yields what we would like to receive, anywhere down the long chain of dependencies. Of course software we build should help us with matching intents we cast to provide [vf:Offer](https://github.com/valueflows/intent/blob/master/Offer.md) with inputs to the transportation process and processes it depends on, as well with intents to receive which all the contributors cast. Here again, access to details of the process which yields resource we intent to receive, can help us with finding a way to reciprocate or even move from consumer role into **prosumer** https://github.com/valueflows/valueflows/issues/118

**Comment by gcassel** [comment]
We must distinguish a transportation service (or function) from any organizations which *provide* such services.  

Casually, people may often call a organization/ company "a bus service"--  but that's *not* how VF wants to use the term "service"... is it?? 

An organization is a very different class of 'entity' (system, really) than the services/ functions which it provides.

There are many related issues, including the main opinion which I've been trying (and perhaps failing) to share.     However, this seems a good point to stop for some clarification.

I perceive a "service" as a desired action, process, change.  People may think in terms of the result of the service, such as "a clean car" or "I arrive in Jersey City" ...   but what we want is for action to occur:  e.g.,   "I want my dirty car to be transformed into a clean car"   or   "I want my location to change from Hoboken to Jersey City".   

I'm saying that the service *is the change*, the action, the process.   

We may desire to *have* a clean car,  but we desire for other people to *perform or regulate a cleaning process.*

Are our terms in sync?

**Comment by elf-pavlik** [comment]
>  People may think in terms of the result of the service, such as "a clean car" or "I arrive in Jersey City" ... but what we want is for action to occur: e.g., "I want my dirty car to be transformed into a clean car" or "I want my location to change from Hoboken to Jersey City".

I think bus transportation gives a good example to analyse difference between the Process, its outputs and Services involved in *vf:Transfer*.

### Process

Bus travel Paris -> Brussels
Seats available: 48

this process gives output which has **potential** to transport 48 people for the whole distance.
in most cases buses don't reach their full potential and the **actual** transport sevices provided for each of the individuals add up to some number of people travelling for some fraction of the distance each one.

### Service

Transportation of elf Pavlik Paris -> Lille

I didn't travel the full distance covered by this Process, also I only consumed a single seat which someone else could use to travel Lille -> Brussels.

I could also have transfer and service I received would combine outputs of two independent transportation processes.

If you look at shipping packages, each shipping service (per page) involves a whole chain of transportation processes which @bhaugen linked to in https://github.com/valueflows/process/issues/9#issuecomment-216789048

**Comment by elf-pavlik** [comment]
How do we relate Service and Work?

**Comment by bhaugen** [comment]
Good issue. I got an email out to the REA gang and am hoping for some tips on service.  Short response for now: work can go into a service. Now to define both better...

**Comment by elf-pavlik** [comment]
From *vf:Process* perspective
* *vf:Work* - subclass of *vf:Resource* which goes into in *vf:Input* in *vf:Process*
* *vf:Service* - subclass of *vf:Resource* which goes out of *vf:Output* in *vf:Process*

so in P -> [O|I] -> P -> [O|I]

*vf:Work* ~= *vf:Service (we may still find some differences)

**Comment by fosterlynn** [comment]
>so in P -> [O|I] -> P -> [O|I]
>vf:Work ~= vf:Service (we may still find some differences)

A Service could include other inputs besides work.  For example Sensorica offers a 3D printing class that they consider to be a service.  Besides work, there are inputs of a space (use), the printer (use), some random filament to do little demo projects in the printer (consume).  Any printer use triggers a transfer of $1.50/hour into the printer maintenance fund, an expense of providing the service.  People take home the little demo things so those aren't really output in the sense of production, they are part of the education.  Anyhow, there is a lot going on there which basically provides an educational service.

**Comment by fosterlynn** [comment]
^ but I think you already have talked about this kind of example, so maybe I missed your point.... ?

**Comment by elf-pavlik** [comment]
If I set my working availability for [21 hours each week](http://www.neweconomics.org/publications/entry/21-hours). Each scheduled commitment should decrement my working availability, so in a way *consume* it. Once I commit all my working time, my personal task management system should worn me if I try to make any more commitments.

Let's say that I always offer my work as service ('independent contractor') and this work service always gets transferred. In my case very often one way transfer representing donation, but in undefined future someone might want to make unexpected and voluntary reciprocal transfer and reference any of my work service transfers.

**Comment by fosterlynn** [comment]
good use case!

**Comment by elf-pavlik** [comment]
I think main difference we can capture for v0.1

*Material resources can get stored and consumed later but services need to get consumed as soon as they get created* 

In one of next releases we should address #40 since creating services which don't get consumed pretty much just wastes inputs consumed by the process which created such 'blank' service.

**Comment by elf-pavlik** [comment]
Thinking of resources as something that connects processes in IPO, same resource comes as output of one process and goes into input of another process. We could think of resources as *Synchronous* and *Asynchronous* elements in IPO chains. So one process needs to output the resource while other process takes it as it's input:

### Asynchronous
* *vf:MaterialResource*
* *vf:CurrencyResource*

### Synchronous
* *vf:ServiceResource*
* *vf:UsageResource*
* *vf:WorkResource*

The process that outputs usage and work still seems unclear, but we have many examples of processes that output services.

**Comment by bhaugen** [comment]
> The process that outputs usage and work still seems unclear, but we have many examples of processes that output services.

I thought we had covered how usage inputs happen. The resources to be used mostly come from the same kinds of processes and exchanges as any other material resource. Once exception is that usage resources usually require ongoing maintenance.

Work resources come from processes of human development and sustenance. Those are important to document in economic ecosystems with reciprocity cycles (as in how do we develop and take care of our people), but probably not worth documenting in the day-to-day work inputs. (I'm not opposed if somebody really wants to do that, but I wouldn't if I was trying to get something done...)

**Comment by fosterlynn** [comment]
>I thought we had covered how usage inputs happen. The resources to be used mostly come from the same kinds of processes and exchanges as any other material resource. Once exception is that usage resources usually require ongoing maintenance.

As of now, I am thinking of usage resources as resources themselves, with vf:underlyingResource of the material item (tool, equipment) that is being used.  So I agree with @elf-pavlik that it is fuzzy how they come into existence.  If we do adopt the underlying resource concept, we will need to use that as a connector in the flows to get back to the actual material resource.

They could come into existence during the use event, or could just exist as a resource that sits there waiting until someone makes use of it.... I will need to do some yaml to work this through.

**Comment by fosterlynn** [comment]
>We could think of resources as Synchronous and Asynchronous elements in IPO chains.

This is an interesting concept.  We do need to understand and document in some way the resources that are being created and consumed at the same time, such as services.

**Comment by bhaugen** [comment]
If you are talking about calendar slots (time:intervals) those start out as commitments, on the plan layer. You all will need to decide whether you consider them to exist as resources at that stage or not.

**Comment by fosterlynn** [comment]
>If you are talking about calendar slots (time:intervals) those start out as commitments, on the plan layer. You all will need to decide whether you consider them to exist as resources at that stage or not.

I am not talking about calendar slots or the plan layer.

**Comment by elf-pavlik** [comment]
> Work resources come from processes of human development and sustenance. Those are important to document in economic ecosystems with reciprocity cycles (as in how do we develop and take care of our people), but probably not worth documenting in the day-to-day work inputs. (I'm not opposed if somebody really wants to do that, but I wouldn't if I was trying to get something done...)

I will add use case where a person providing one's work as service needs to first transport oneself to the workplace. In such case, to have that work resource output we will have dependency on a process which transports the person to the workplace. In IPO chains I would like to have clear way of traversing inter-dependencies of various processes.

**Comment by fosterlynn** [comment]
We've been chatting in gitter, partly about Service.  Some questions we have tossed around are: 
* are there services that are internal to a context?
* when do you need to create a vf:Resource for a service?
* do you ever need service as a resource to bridge between processes in IPO chains? if so, when? or is it more transfer related?
* does it make a difference if there is a material resource also involved?  (e.g. repairing something; transporting something; vs training someone or providing dental services (although there was discussion of teeth or skills being resources))

Some of this is starting to settle in my mind, but still very tentatively :) - putting here for further discussion. 

Services are given to other agents, I can't think of examples where an agent would provide a service to itself.  Regarding agents, I think context agents are irrelevant to the discussion.  What is important is what we in NRP call from agents and to agents.  (Other names have been discussed for vf - provider and receiver, performer of work, ....)  One agent could provide a service to another agent within a context, or crossing the context boundary.  Context is a level up.  Or out, depending on the mental image you like.

Right now I think services always imply a transfer.  A service given is de-facto transferred to the other agent.  Maybe there will be something transferred in exchange for the service or not.  But a transfer has occurred.

It seems like services that involve material items (like repairing or transporting) don't need to create a service resource unless there is a transfer involved.  For material items, there is a workflow or transportation kind of process, and that is enough.  But if transporting or repairing will be exchanged, then a service can be created so that there is something (a resource) to be transferred.

Seems like there could be a couple ways to do this:

1. vf:produce a service resource (not inventoried?) as output of the process of providing the service.  Or maybe there is a different better verb.  Then create a vf:transfer of the service resource to the person who received it.

2. vf:transfer a service resource as output of the process.  The transfer has in fact occurred.

Even though 2. is a bit radical for the REA concensus of processes and transfers(exchanges) being separate things, I like that it seems to more accurately reflect reality, and is simpler.  Two events, one for creation and one for transfer, seems artificial in some way.

Note service is needed when there are more than one input to a process. Could be optional if there is only work.  I don't have any problem with being able to transfer vf:work without creating a process with just work as input and a service as output. Or one could create the service.

What of this makes sense and what doesn't?

**Comment by elf-pavlik** [comment]
> Even though 2. is a bit radical for the REA concensus of processes and transfers(exchanges) being separate things, I like that it seems to more accurately reflect reality, and is simpler. Two events, one for creation and one for transfer, seems artificial in some way.

👎 to mixing processes and transfers, I'd like to make sure that we keep them orthogonal. only process affects resources, transfers(exchanges) affect relationships between agents and resources. currently we try using `vf:IPOEvent` to make it clear that we talk about process related events and not transfers.

**Comment by elf-pavlik** [comment]
I think modeling service still needs quite some work and we need to patiently work on it. Few observations

> Right now I think services always imply a transfer. A service given is de-facto transferred to the other agent. Maybe there will be something transferred in exchange for the service or not. But a transfer has occurred.
[...]
But if transporting or repairing will be exchanged, then a service can be created so that there is something (a resource) to be transferred.

If we have instance of *vf:Service* which has *vf:provider* and *vf:recipient* relationship to instances of *vf:Agent*. I don't think we also need **additional** *vf:Transfer* for it with some kind of *from* & *to* relationships! *from* = *provider* & *to* = *recipient*. We could see if in exchanges *vf:Transfer* of some product could have reciprocal relation directly to a Service.

> vf:produce a service resource (not inventoried?) as output of the process of providing the service. Or maybe there is a different better verb. Then create a vf:transfer of the service resource to the person who received it.

I don't see *vf:Service* fitting IPO chains as *input* neither *output* of a process. We should explore how Service can relate to Process and/or IPOEvent. If we take an example of 'transportation service' which involved multiple *vf:Transportation* processes. We can't point a single process which would 'output' that service.

In general, description of IPO chain shouldn't depend on how many distinct agents have some relationships to it (let's not jump into special case of Work right away), IPO description should stay the same no matter if agent who makes effort also benefits from executing a process or some other agent(s) benefit from it. It should also not depend on agent <-> resource relationships. Information about who owned which inputs and which outputs to the process should augment IPO information but doesn't belong to the description of IPO chain.

As another example of particular IPO description which we can augment differently depending on agreements between agents - *a run of some truck moving various stuff between various location* - depending on, if someone requested that particular movement of stuff or not, we will find there related service(s) or not. IPO description of above, should stay **exactly the same** when:
* agent who executed the transportation process also requested it (same agent makes effort and benefits)
* other agent(s) requested movement of transported goods (one agent makes effort and other benefits)
* no one requested movement of resources and it happened as accident (one agent makes effort and no one benefits)

Of course all those aspects related to agreements between agents, who makes effort and who benefits stay fundamental to describing those economic happenings. Still IMO we should keep description of IPO chains independent of that and augment them with that information / overlay it over IPO chain similar as *vf:Transfer* of agent <-> resource relationship augment the IPO information.
