### ISSUE TITLE
examples use two different *maintainer* properties

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/resource#9]
- https://github.com/valueflows/resource/blob/master/examples/valueflows.jsonld#L14
- https://github.com/valueflows/resource/blob/master/examples/holodex.jsonld#L16

While example [package.json in npm](https://docs.npmjs.com/files/package.json) defines properties like _auhor_ or _dependencies_ used in thousands of packages. We already among 4 of us have two different properties. IMO current situation will not allow us to make simple queries as "All the resources which Mikey maintains".

**Comment by ahdinosaur** [comment]
this was intentional, which led to a long Gitter chat:

>
elf-pavlik: BTW now we have two unrelated ways of stating maintainer relationship
ahdinosaur: yay
elf-pavlik: https://github.com/valueflows/resource/blob/master/examples/valueflows.jsonld#L14
no search or filtering in this situation
each system will consider it as two unrelated relationships
ahdinosaur: @elf-pavlik well we could sameAs or related semantics
elf-pavlik: rdfs:subPropertyOf could do
if we see one more specific then the other one
ahdinosaur: i honestly don't want to support globalization ("one single truth to unite them all")
i prefer local semantics
elf-pavlik: if we see them equivalent than owl:equivalentProperty
ahdinosaur: cool, should be good to document somewhere
elf-pavlik: do you run RDFS reasoner on data?
while ontologies support such alignment, someone still needs to build reasoners
bhaugen: @elf-pavlik - not sure what you mean by
elf-pavlik: for example in JS to run in 'native web apps' http://rdfjs.org
bhaugen:
> support globalization ("one single truth to unite them all")
ahdinosaur: @elf-pavlik we're on a long journey, slow and steady
bhaugen: While the global Internet survives, I'm really interested in having global economic networks
but I also like the P2P Foundation idea of heavy local, light global
ahdinosaur: @bhaugen i agree, but i imagine you see that as small local networks overlapping into larger and larger networks
bhaugen: but that doesn't mean one single truth
elf-pavlik: we have interesting use case here
bhaugen: I think things are happening in all directions at the same time
elf-pavlik: @ahdinosaur and I use different properties to state 'maintainer' type of relationship
bhaugen: some global first (like this project)
some local first
not tied together very much
ahdinosaur: the distinction i'm making is about an abstract vocabulary versus a global vocabulary. i want us to do the former not the latter.
bhaugen: Sensorica is an example of something that started local and went global
ahdinosaur: an abstract vocabulary leaves types up to the user, while a global vocabulary defines a set of types
elf-pavlik: if we decide to start with rdfs:subPropertyOf and/or owl:equivalentProperty than we better make sure that apps we build use RDFS/OWL reasoning
i see need for both
bhaugen: We totally believe in local vocabularies
elf-pavlik: i see need for all three :smile:
bhaugen: that's part of the backstory for wanting user defined names for relationships
elf-pavlik: @bhaugen so no shared understanding about types across instances?
juts basic 'grammar'?
bhaugen: @elf-pavlik - please name all three?
ahdinosaur: i think we all agree here
bhaugen: yes, shared understanding about types
I think some set of global or at least commonly used types
elf-pavlik: 1) upper ontology / abstract vocabulary / basic grammar
bhaugen: the local names fit into the common types
elf-pavlik: 2) taxonomies / common types
3) local extensions to 2)
bhaugen: domain ontologies?
ahdinosaur: uh, what about local types that don't extend global types?
elf-pavlik: maintainer doesn't seem like a case here
bhaugen: @ahdinosaur good question
maybe a way to promote new local types into the common typology
ahdinosaur: @elf-pavlik agree. please realize i'm being hard about maintainer because i'm making it a use case on purpose.
bhaugen:
> maintainer doesn't seem like a case here
case of what?
ahdinosaur: of a local type not matching a global type
bhaugen: ok
elf-pavlik: @bhaugen yes for converging independent termshttps://www.w3.org/wiki/Socialwg/Social_syntax/User_Stories#Converging_vocabulary_terms
ahdinosaur: but i'm against global types in general, so hence my use case (edit: came out wrong, sleepy)
bhaugen: @ahdinosaur we find common types for the local names to be needed
we attach behaviors to the types
elf-pavlik: @ahdinosaur so you see 'maintainer' as not shared (even to some extent) concept ?
bhaugen: so until we can include the operational behaviors in the vocabs
we're attaching code
to a set of controlled types that we can depend on existing
@elf-pavlik updated link to convergence of terms use casehttps://www.w3.org/wiki/Socialwg/Social_syntax/User_Stories#Converging_vocabulary_terms
ahdinosaur: @elf-pavlik i do, but i guess my point is that agents share semantics, not some unidentified global agent
so maintainer might be a type brought to us by the Open App Ecosystem agent, or something
elf-pavlik: @ahdinosaur I don't understand what you mean by "not some unidentified global agent"
@ahdinosaur possibly relevant to 'unidentified agent' https://github.com/valueflows/valueflows/issues/71#issuecomment-148914794
we talk a 'maintainer' type of relationship, not an agent of type 'Maintainer' ?
ahdinosaur: @elf-pavlik more relevant to 'unidentified agent' is https://github.com/valueflows/valueflows/pull/65#issuecomment-147872217, but it's really just a feeling based on my feelings toward global peer-to-peer networks: https://blog.dinosaur.is/global-vs-local-systems/
elf-pavlik: @ahdinosaur I still don't get the 'agent' part
ahdinosaur: my feeling is that everything should be centered in agents. in whom is the 'maintainer' relationship type centered?
the Value Flows agent? that's fine with me
elf-pavlik: what do you mean by 'centered' ?
relationship has two sides (if we don't go into n-ary relations) and no center
ahdinosaur: as in who holds the culture, since types are semantics are culture.
elf-pavlik: @ahdinosaur I recommend you taking a look at http://patterns.dataincubator.org/book/materialize-inferences.html
this way we can avoid need for introducing reasoners
ahdinosaur: my feeling is globalization destroys culture by normalizing diverse sets of cultures into a single uniform culture, i don't want to support uniformity, but i am fine with us creating and holding our own culture.
elf-pavlik: and experiment with options like "vf:relationsip": [ "dex:relationshipTypes/is-maintained-by", "role:maintainer" ]
ahdinosaur: eh, really brittle
elf-pavlik: let's all make power plugs the way we like to design them locally :wink:
ahdinosaur: hehe
elf-pavlik: wait, we had it with phone chargers... brand culture
ahdinosaur: all hail the singularity
elf-pavlik: @ahdinosaur how do you expect an app to understand 'maintainer' relationship type across systems?
ahdinosaur: each 'maintainer' type can reference other 'maintainer' types that it relates to
popular 'maintainer' types will arise which many people reference
elf-pavlik:
:-1: for commonly understood author in https://docs.npmjs.com/files/package.json ?
do you have in holodex package.json instead of "author" "dex:relationshipTypes/is-authored-by"? ... going to check
ahdinosaur: hahaha
elf-pavlik: https://github.com/holodex/app/blob/master/package.json#L39
ahdinosaur: don't take me too seriously :cat:
elf-pavlik: should I make PR ?
I can include switch to "dex:relationshipTypes/is-dependent-on" forhttps://github.com/holodex/app/blob/master/package.json#L55
npm install will just love it!
ahdinosaur: i'm took a stance on the opposite side of the spectrum so we don't forget about that side. obviously i'm not that extreme, i also like to play around.
elf-pavlik: @ahdinosaur I need to go cook some food, let's discuss it further next time?
I think you may really like my argument in https://github.com/valueflows/valueflows/issues/71#issuecomment-148914794
ahdinosaur: keen, i need to sleep though
yeah, i do


after sleeping on it, what i wanted to communicate was there are many ways of communicating similar yet subtly different semantics, i don't want us to necessarily normalize these differences into unified singular semantics, because i think diversity of semantics is a good thing. i brought up globalization because that is a human phenomenon where diverse cultures are entirely erased due to this normalization, i'm interested in reversing this trend by supporting local semantics first over global semantics.

making a `dex:maintains` relationship instead of using `role:maintain` probably isn't the best example for this, but it does address the use case of me wanting to own my local semantics, as i might have a subtly different definition of `maintains` than someone else. in this case, `dex:maintains` should use `owl:equivalentProperty` to point to [`vf:maintains`](https://github.com/valueflows/agent/issues/38)  (see also: https://github.com/valueflows/valueflows/pull/65#issuecomment-147872217).

**Comment by elf-pavlik** [comment]
@ahdinosaur I would propose to capture you use case in example which may cause less confusion among people who would like to simply use common way to for example relate npm package to person maintaining it. Of course we can try with two different properties which will link you as maintainer to holodex software and valueflows vocab. Actually I would really like to see how holodex will handle it, also in terms of https://github.com/valueflows/valueflows/issues/67

Let's than just leave it this way with two different properties and focus on loading all this test data into holodex first?
